### ISSUE TITLE
Erro ao cadastrar nova música

### ISSUE THREAD

**Issue by nerijunior** [sntpiraquara/playlist#1]
@GuiRufino existe um problema, ao cadastrar uma música nova a mensagem "Musica Cadastrada!" aparece na tela, mas ela não é cadastrada:

## Como reproduzir:

Alterar o nome da base de dados no `db.php` e teste.

**Comment by GuiRufino** [comment]
updates ready!

**Comment by GuiRufino** [comment]
tenta ai agora veeei
